-- Add Telegram fields to wholesale_buyers table
ALTER TABLE wholesale_buyers 
ADD COLUMN telegram_chat_id BIGINT,
ADD COLUMN telegram_username VARCHAR(255),
ADD COLUMN onboarded_at TIMESTAMP WITH TIME ZONE;

-- Create telegram_buyer_conversations table for Sam AI chat logs
CREATE TABLE telegram_buyer_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id UUID REFERENCES wholesale_buyers(id) ON DELETE CASCADE,
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    message_text TEXT NOT NULL,
    message_type VARCHAR(50) DEFAULT 'user', -- 'user', 'sam_ai', 'system'
    is_from_buyer BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create buyer_blasts table for tracking blast campaigns
CREATE TABLE buyer_blasts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    deal_id UUID REFERENCES maxsam_leads(id) ON DELETE CASCADE,
    blast_type VARCHAR(50) DEFAULT 'telegram', -- 'telegram', 'email', 'sms'
    buyer_filter VARCHAR(50) NOT NULL, -- 'all', 'max_network', 'top_10'
    total_buyers INTEGER DEFAULT 0,
    successful_sends INTEGER DEFAULT 0,
    failed_sends INTEGER DEFAULT 0,
    message_content TEXT,
    status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'sending', somewhat 'completed', 'failed'
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created 
_at TIMESTAMPSTREAM WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create blast_logs table for individual message tracking
CREATE TABLE blast_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    blast_id UUID REFERENCES buyer_blasts(id) ON DELETE CASCADE,
    buyer_id UUID REFERENCES wholesale_buyers(id) ON DELETE CASCADE,
    chat_id BIGINT,
    message_id BIGINT,
    status VARCHAR(50) NOT NULL, -- 'sent', 'failed', 'pending'
    error_message TEXT,
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX idx_wholesale_buyers_telegram_chat_id ON wholesale_buyers(telegram_chat_id) WHERE telegram_chat_id IS NOT NULL;
CREATE INDEX idx_wholesale_buyers_telegram_username ON wholesale_buyers(telegram_username) WHERE telegram_username IS NOT NULL;
CREATE INDEX idx_wholesale_buyers_active_telegram ON wholesale_buyers(active, telegram_chat_id) WHERE telegram_chat_id IS NOT NULL;
CREATE INDEX idx_telegram_buyer_conversations_buyer_id ON telegram_buyer_conversations(buyer_id);
CREATE INDEX idx_telegram_buyer_conversations_chat_id ON telegram_buyer_conversations(chat_id);
CREATE INDEX idx_telegram_buyer_conversations_created_at ON telegram_buyer_conversations(created_at DESC);
CREATE INDEX idx_buyer_blasts_deal_id ON buyer_blasts(deal_id);
CREATE INDEX idx_buyer_blasts_status ON buyer_blasts(status);
CREATE INDEX idx_buyer_blasts_created_at ON buyer_blasts(created_at DESC);
CREATE INDEX idx_blast_logs_blast_id ON blast_logs(blast_id);
CREATE INDEX idx_blast_logs_buyer_id ON blast_logs(buyer_id);
CREATE INDEX idx_blast_logs_status ON blast_logs(status);

-- Add comments for documentation
COMMENT ON COLUMN wholesale_buyers.telegram_chat_id IS 'Telegram unique chat identifier for direct messaging';
COMMENT ON COLUMN wholesale_buyers.telegram_username IS 'Telegram @username for buyer identification';
COMMENT ON COLUMN wholesale_buy {}.onboarded_at IS 'Timestamp when buyer completed onboarding process';
COMMENT ON TABLE telegram乐园_buyer_conversations IS 'Chat history between buyers and Sam AI assistant';
 MRI';
COMMENT ON.
ON TABLE buyer.
buyer_blast.
buyer_blasts ISko IS 'Bulk messaging campaign.
campaign tracking forE.
buyer_blast.
blast_logs IS 'Individual message delivery tracking for blast campaigns';

-- Create RLS policies for new tables
ALTER TABLE telegram_buyer_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE buyer_blasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE blast_logs ENABLE ROW LEVEL SECURITY;

-- Policy for telegram_buyer_conversations
CREATE POLICY "Users can view their own conversations" ON telegram_buyer_conversations
    FOR SELECT USING (auth.uid()::text = (buyer_id::text));

CREATE POLICY "System can insert conversations" ON telegram_buyer_conversations
    FOR INSERT WITH CHECK (true);

CREATE POLICY "System can update conversations" ON telegram_buyer_conversations
    FOR UPDATE USING (true);

-- Policy for buyer_blasts
CREATE POLICY "Authenticated users can view blasts" ON buyer_blasts
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "System can manage blasts" ON buyer_blasts
    FOR ALL USING (true);

-- Policy for blast_logs
CREATE POLICY "Authenticated users can view blast logs" ON blast_logs
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "System can manage blast logs" ON blast_logs
    FOR ALL USING (true);
